import { Type } from "@google/genai";

export const ANSWER_COACH_SCHEMA = {
  type: Type.OBJECT,
  properties: {
    scoreOutOf10: { type: Type.NUMBER },
    scorePercent: { type: Type.NUMBER },
    isGood: { type: Type.BOOLEAN },
    correctness: { type: Type.STRING },
    technicalAccuracy: { type: Type.STRING },
    completeness: { type: Type.STRING },
    communicationQuality: { type: Type.STRING },
    confidence: { type: Type.STRING },
    missingPoints: { type: Type.ARRAY, items: { type: Type.STRING } },
    incorrectStatements: { type: Type.ARRAY, items: { type: Type.STRING } },
    strengths: { type: Type.ARRAY, items: { type: Type.STRING } },
    weaknesses: { type: Type.ARRAY, items: { type: Type.STRING } },
    idealAnswerKeyPoints: { type: Type.ARRAY, items: { type: Type.STRING } },
    bestPractices: { type: Type.ARRAY, items: { type: Type.STRING } },
    commonMistakes: { type: Type.ARRAY, items: { type: Type.STRING } },
    interviewerExpectations: { type: Type.STRING },
    coachingTips: { type: Type.ARRAY, items: { type: Type.STRING } },
    betterAnswer: { type: Type.STRING },
    whyGood: { type: Type.ARRAY, items: { type: Type.STRING } },
    whyWeak: { type: Type.ARRAY, items: { type: Type.STRING } },
    betterVersion: { type: Type.STRING },
    industryAnswer: { type: Type.STRING },
    recruiterView: { type: Type.STRING },
    weakPoints: { type: Type.ARRAY, items: { type: Type.STRING } },
    strongPoints: { type: Type.ARRAY, items: { type: Type.STRING } },
    followUpType: { type: Type.STRING },
    followUpQuestion: { type: Type.STRING },
    shouldAdvanceQuestion: { type: Type.BOOLEAN },
    interviewerResponse: { type: Type.STRING },
    topicTag: { type: Type.STRING },
  },
  required: [
    "scoreOutOf10",
    "scorePercent",
    "isGood",
    "correctness",
    "technicalAccuracy",
    "completeness",
    "communicationQuality",
    "confidence",
    "missingPoints",
    "incorrectStatements",
    "strengths",
    "weaknesses",
    "idealAnswerKeyPoints",
    "coachingTips",
    "betterAnswer",
    "interviewerResponse",
    "shouldAdvanceQuestion",
    "topicTag",
  ],
};

/** @deprecated Use ANSWER_COACH_SCHEMA */
export const ANSWER_ANALYSIS_SCHEMA = ANSWER_COACH_SCHEMA;

export const POST_INTERVIEW_COACHING_ITEM_SCHEMA = {
  type: Type.OBJECT,
  properties: {
    questionIndex: { type: Type.NUMBER },
    scoreOutOf10: { type: Type.NUMBER },
    technicalAccuracy: { type: Type.STRING },
    communication: { type: Type.STRING },
    confidence: { type: Type.STRING },
    completeness: { type: Type.STRING },
    clarity: { type: Type.STRING },
    whatYouDidWell: { type: Type.ARRAY, items: { type: Type.STRING } },
    whatYouMissed: {
      type: Type.OBJECT,
      properties: {
        missingConcepts: { type: Type.ARRAY, items: { type: Type.STRING } },
        missingKeywords: { type: Type.ARRAY, items: { type: Type.STRING } },
        missingTechnicalDetails: { type: Type.ARRAY, items: { type: Type.STRING } },
        weakExplanations: { type: Type.ARRAY, items: { type: Type.STRING } },
        incorrectStatements: { type: Type.ARRAY, items: { type: Type.STRING } },
        communicationProblems: { type: Type.ARRAY, items: { type: Type.STRING } },
        whyItMatters: { type: Type.STRING },
      },
      required: [
        "missingConcepts",
        "missingKeywords",
        "missingTechnicalDetails",
        "weakExplanations",
        "incorrectStatements",
        "communicationProblems",
        "whyItMatters",
      ],
    },
    idealInterviewAnswer: { type: Type.STRING },
    whyStrongAnswer: { type: Type.STRING },
    comparison: {
      type: Type.OBJECT,
      properties: {
        whatMissed: { type: Type.ARRAY, items: { type: Type.STRING } },
        whatToImprove: { type: Type.ARRAY, items: { type: Type.STRING } },
        pointsToAdd: { type: Type.ARRAY, items: { type: Type.STRING } },
        partsToRemoveOrSimplify: { type: Type.ARRAY, items: { type: Type.STRING } },
      },
      required: [
        "whatMissed",
        "whatToImprove",
        "pointsToAdd",
        "partsToRemoveOrSimplify",
      ],
    },
    practiceVersion: { type: Type.STRING },
    interviewTips: { type: Type.ARRAY, items: { type: Type.STRING } },
    difficultyLevel: { type: Type.STRING },
    difficultyExplanation: { type: Type.STRING },
    recommendedPractice: { type: Type.ARRAY, items: { type: Type.STRING } },
    topicTag: { type: Type.STRING },
  },
  required: [
    "questionIndex",
    "scoreOutOf10",
    "technicalAccuracy",
    "communication",
    "confidence",
    "completeness",
    "clarity",
    "whatYouDidWell",
    "whatYouMissed",
    "idealInterviewAnswer",
    "whyStrongAnswer",
    "comparison",
    "practiceVersion",
    "interviewTips",
    "difficultyLevel",
    "difficultyExplanation",
    "recommendedPractice",
  ],
};

export const POST_INTERVIEW_COACHING_BATCH_SCHEMA = {
  type: Type.OBJECT,
  properties: {
    coachings: {
      type: Type.ARRAY,
      items: POST_INTERVIEW_COACHING_ITEM_SCHEMA,
    },
  },
  required: ["coachings"],
};
